export default [    
            {
            "clan_id": "167",
            "clan_rank": "0",
            "clan_name": "OG",
            "owner_id": "960",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "185",
            "clan_rank": "0",
            "clan_name": "อั๊ยย่ะ",
            "owner_id": "1073",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "208",
            "clan_rank": "0",
            "clan_name": "NAYNY02",
            "owner_id": "1261",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "202",
            "clan_rank": "0",
            "clan_name": "ผลไม้",
            "owner_id": "1113",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "170",
            "clan_rank": "0",
            "clan_name": "ตายาย",
            "owner_id": "1043",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "171",
            "clan_rank": "0",
            "clan_name": "101SLaBeL",
            "owner_id": "1050",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "196",
            "clan_rank": "0",
            "clan_name": "LilGang223",
            "owner_id": "1182",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "381",
            "clan_rank": "0",
            "clan_name": "MVP",
            "owner_id": "2434",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "186",
            "clan_rank": "0",
            "clan_name": "OTPZONE",
            "owner_id": "1029",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "192",
            "clan_rank": "0",
            "clan_name": "ผลไม้รวม",
            "owner_id": "1120",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "382",
            "clan_rank": "0",
            "clan_name": "THEBANK",
            "owner_id": "2013",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "168",
            "clan_rank": "0",
            "clan_name": "สลาย",
            "owner_id": "1017",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "176",
            "clan_rank": "0",
            "clan_name": "กองทัพขยะ",
            "owner_id": "963",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "187",
            "clan_rank": "0",
            "clan_name": "BTS",
            "owner_id": "1066",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "177",
            "clan_rank": "0",
            "clan_name": "ธรรมดา",
            "owner_id": "1051",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "219",
            "clan_rank": "0",
            "clan_name": "OoGalaxyoO",
            "owner_id": "1285",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "197",
            "clan_rank": "0",
            "clan_name": "กระเทยมาแล้ว",
            "owner_id": "1185",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "384",
            "clan_rank": "0",
            "clan_name": "Xsus",
            "owner_id": "1226",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "193",
            "clan_rank": "0",
            "clan_name": "Insurgent",
            "owner_id": "981",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "375",
            "clan_rank": "0",
            "clan_name": "สะมะโหสะมะเห",
            "owner_id": "1702",
            "create_date": "20191107",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "189",
            "clan_rank": "0",
            "clan_name": "SpecialForce",
            "owner_id": "1126",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "174",
            "clan_rank": "0",
            "clan_name": "Universe",
            "owner_id": "1040",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "190",
            "clan_rank": "0",
            "clan_name": "ชุนเติ้ลลิน",
            "owner_id": "1132",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "182",
            "clan_rank": "0",
            "clan_name": "Killdog",
            "owner_id": "988",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "181",
            "clan_rank": "0",
            "clan_name": "Attackxx",
            "owner_id": "971",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "191",
            "clan_rank": "0",
            "clan_name": "BGZ",
            "owner_id": "1130",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "184",
            "clan_rank": "0",
            "clan_name": "AttackAllAround",
            "owner_id": "1090",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "169",
            "clan_rank": "0",
            "clan_name": "PoWerJET",
            "owner_id": "1019",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "217",
            "clan_rank": "0",
            "clan_name": "คนตาย",
            "owner_id": "1303",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "198",
            "clan_rank": "0",
            "clan_name": "ไม่ห้าวก้ไม่ตาย",
            "owner_id": "1215",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "194",
            "clan_rank": "0",
            "clan_name": "77NoSutekiMachi",
            "owner_id": "1176",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "200",
            "clan_rank": "0",
            "clan_name": "ยิงคมจนเป็นลม",
            "owner_id": "1217",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "212",
            "clan_rank": "0",
            "clan_name": "สลายOver",
            "owner_id": "1016",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "204",
            "clan_rank": "0",
            "clan_name": "พลังประชารัฐ",
            "owner_id": "1146",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "201",
            "clan_rank": "0",
            "clan_name": "Onname",
            "owner_id": "1200",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "222",
            "clan_rank": "0",
            "clan_name": "aaaa",
            "owner_id": "1291",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "205",
            "clan_rank": "0",
            "clan_name": "babei",
            "owner_id": "1098",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "206",
            "clan_rank": "0",
            "clan_name": "Hero",
            "owner_id": "1124",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "207",
            "clan_rank": "0",
            "clan_name": "เกิดมาใหญ่",
            "owner_id": "1250",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "210",
            "clan_rank": "0",
            "clan_name": "รัสเซีย",
            "owner_id": "1259",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "214",
            "clan_rank": "0",
            "clan_name": "จม",
            "owner_id": "1275",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "211",
            "clan_rank": "0",
            "clan_name": "lBiglBosslBabyl",
            "owner_id": "1239",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "215",
            "clan_rank": "0",
            "clan_name": "สมาคม007",
            "owner_id": "1083",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "216",
            "clan_rank": "0",
            "clan_name": "000",
            "owner_id": "1279",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "188",
            "clan_rank": "0",
            "clan_name": "MITHMadeinThai",
            "owner_id": "1079",
            "create_date": "20191101",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "218",
            "clan_rank": "0",
            "clan_name": "OECHAI",
            "owner_id": "1007",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "220",
            "clan_rank": "0",
            "clan_name": "AAA",
            "owner_id": "1031",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "221",
            "clan_rank": "0",
            "clan_name": "Koye",
            "owner_id": "1307",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "223",
            "clan_rank": "0",
            "clan_name": "7G",
            "owner_id": "1313",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "225",
            "clan_rank": "0",
            "clan_name": "นรก2019",
            "owner_id": "1326",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "241",
            "clan_rank": "0",
            "clan_name": "มังกรแดงอยากโดน",
            "owner_id": "1422",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "224",
            "clan_rank": "0",
            "clan_name": "ย่องมายิง3",
            "owner_id": "1304",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "226",
            "clan_rank": "0",
            "clan_name": "wายุทะเลทราย",
            "owner_id": "1324",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "242",
            "clan_rank": "0",
            "clan_name": "ลั่นแจ๊ะโหดสัส",
            "owner_id": "1427",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "228",
            "clan_rank": "0",
            "clan_name": "MCSeksin",
            "owner_id": "1315",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "374",
            "clan_rank": "0",
            "clan_name": "ExpEsport",
            "owner_id": "2363",
            "create_date": "20191107",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "251",
            "clan_rank": "0",
            "clan_name": "ULTIMATEKING",
            "owner_id": "1472",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "230",
            "clan_rank": "0",
            "clan_name": "pmy99",
            "owner_id": "1357",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "376",
            "clan_rank": "0",
            "clan_name": "เฒ่าแก่",
            "owner_id": "1566",
            "create_date": "20191107",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "273",
            "clan_rank": "0",
            "clan_name": "SupreameIV",
            "owner_id": "1628",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "243",
            "clan_rank": "0",
            "clan_name": "โลมา",
            "owner_id": "1212",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "245",
            "clan_rank": "0",
            "clan_name": "FTR",
            "owner_id": "1055",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "231",
            "clan_rank": "0",
            "clan_name": "ซoง",
            "owner_id": "1366",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "246",
            "clan_rank": "0",
            "clan_name": "แบกฉีหนีไฟ",
            "owner_id": "1423",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "233",
            "clan_rank": "0",
            "clan_name": "NANIahhhhhhh",
            "owner_id": "1129",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "276",
            "clan_rank": "0",
            "clan_name": "Ninja",
            "owner_id": "1642",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "279",
            "clan_rank": "0",
            "clan_name": "Belleiki",
            "owner_id": "1665",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "236",
            "clan_rank": "0",
            "clan_name": "Bring",
            "owner_id": "1389",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "258",
            "clan_rank": "0",
            "clan_name": "๑Evo๑",
            "owner_id": "1506",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "281",
            "clan_rank": "0",
            "clan_name": "SOCIAL",
            "owner_id": "1700",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "240",
            "clan_rank": "0",
            "clan_name": "วอล์ล",
            "owner_id": "1426",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "254",
            "clan_rank": "0",
            "clan_name": "TheGhostUnit",
            "owner_id": "1488",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "249",
            "clan_rank": "0",
            "clan_name": "HappyThailand",
            "owner_id": "1131",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "255",
            "clan_rank": "0",
            "clan_name": "StarPlatinum",
            "owner_id": "1490",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "248",
            "clan_rank": "0",
            "clan_name": "0oพลเอกประยุดo0",
            "owner_id": "1444",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "250",
            "clan_rank": "0",
            "clan_name": "ไปทางไหนใจก็เจ็บ",
            "owner_id": "1345",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "261",
            "clan_rank": "0",
            "clan_name": "นัมเบอร์วัน",
            "owner_id": "1504",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "232",
            "clan_rank": "0",
            "clan_name": "JoKer",
            "owner_id": "1060",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "274",
            "clan_rank": "0",
            "clan_name": "๛จม",
            "owner_id": "1630",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "259",
            "clan_rank": "0",
            "clan_name": "YIBAMBE",
            "owner_id": "1502",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "227",
            "clan_rank": "0",
            "clan_name": "SOLA",
            "owner_id": "1937",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "235",
            "clan_rank": "0",
            "clan_name": "มหามุณีกาแลกซี่",
            "owner_id": "1393",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "263",
            "clan_rank": "0",
            "clan_name": "X3E",
            "owner_id": "1533",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "269",
            "clan_rank": "0",
            "clan_name": "RatthaphumNT",
            "owner_id": "1563",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "271",
            "clan_rank": "0",
            "clan_name": "AttrackAllAround",
            "owner_id": "1036",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "267",
            "clan_rank": "0",
            "clan_name": "STARTOS",
            "owner_id": "1556",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "287",
            "clan_rank": "0",
            "clan_name": "GCGE",
            "owner_id": "1653",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "277",
            "clan_rank": "0",
            "clan_name": "มือปืนยมทูต",
            "owner_id": "1657",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "282",
            "clan_rank": "0",
            "clan_name": "ยิงเเต่ลม",
            "owner_id": "1638",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "280",
            "clan_rank": "0",
            "clan_name": "DemonIIspado",
            "owner_id": "1686",
            "create_date": "20191103",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "285",
            "clan_rank": "0",
            "clan_name": "ซ่องดูฮี",
            "owner_id": "1713",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "284",
            "clan_rank": "0",
            "clan_name": "สไนเปอร์",
            "owner_id": "1716",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "290",
            "clan_rank": "0",
            "clan_name": "แอนนาเบล",
            "owner_id": "1752",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "286",
            "clan_rank": "0",
            "clan_name": "ALITTA",
            "owner_id": "1595",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "289",
            "clan_rank": "0",
            "clan_name": "อร่อยเฉย",
            "owner_id": "1558",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "291",
            "clan_rank": "0",
            "clan_name": "กัญชา",
            "owner_id": "1732",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "292",
            "clan_rank": "0",
            "clan_name": "AimbotGang",
            "owner_id": "1754",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "293",
            "clan_rank": "0",
            "clan_name": "Highlight",
            "owner_id": "1775",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "247",
            "clan_rank": "0",
            "clan_name": "RPG",
            "owner_id": "1431",
            "create_date": "20191102",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "296",
            "clan_rank": "0",
            "clan_name": "ยมบาล",
            "owner_id": "1811",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "309",
            "clan_rank": "0",
            "clan_name": "ฉลาม",
            "owner_id": "1889",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "345",
            "clan_rank": "0",
            "clan_name": "MINIMART",
            "owner_id": "2094",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "298",
            "clan_rank": "0",
            "clan_name": "Innovate",
            "owner_id": "1843",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "351",
            "clan_rank": "0",
            "clan_name": "XD",
            "owner_id": "2092",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "377",
            "clan_rank": "0",
            "clan_name": "HiiYesJim1669",
            "owner_id": "2264",
            "create_date": "20191107",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "312",
            "clan_rank": "0",
            "clan_name": "UP",
            "owner_id": "1821",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "299",
            "clan_rank": "0",
            "clan_name": "พราย",
            "owner_id": "1828",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "331",
            "clan_rank": "0",
            "clan_name": "สไนเป๏ร์",
            "owner_id": "1996",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "330",
            "clan_rank": "0",
            "clan_name": "littlehope",
            "owner_id": "1872",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "346",
            "clan_rank": "0",
            "clan_name": "ทศกัณฐ์",
            "owner_id": "1902",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "301",
            "clan_rank": "0",
            "clan_name": "FTordered",
            "owner_id": "1445",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "385",
            "clan_rank": "0",
            "clan_name": "Glamorous",
            "owner_id": "2255",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "342",
            "clan_rank": "0",
            "clan_name": "JonEห้าร้oe",
            "owner_id": "2072",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "305",
            "clan_rank": "0",
            "clan_name": "liquid",
            "owner_id": "1882",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "349",
            "clan_rank": "0",
            "clan_name": "ซากุระ",
            "owner_id": "2095",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "306",
            "clan_rank": "0",
            "clan_name": "เค็มปี๋จุ๊กกุ้วว",
            "owner_id": "1807",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "387",
            "clan_rank": "0",
            "clan_name": "25162",
            "owner_id": "1680",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "314",
            "clan_rank": "0",
            "clan_name": "๑PaLaDiN๑",
            "owner_id": "1470",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "324",
            "clan_rank": "0",
            "clan_name": "yousmlie",
            "owner_id": "1158",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "310",
            "clan_rank": "0",
            "clan_name": "FAIR",
            "owner_id": "1890",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "325",
            "clan_rank": "0",
            "clan_name": "BMWs1000RR",
            "owner_id": "1970",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "315",
            "clan_rank": "0",
            "clan_name": "Joker",
            "owner_id": "1935",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "317",
            "clan_rank": "0",
            "clan_name": "dekdee",
            "owner_id": "1883",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "334",
            "clan_rank": "0",
            "clan_name": "Soeriyen",
            "owner_id": "1839",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "318",
            "clan_rank": "0",
            "clan_name": "TFOX",
            "owner_id": "1949",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "389",
            "clan_rank": "0",
            "clan_name": "SoD0407",
            "owner_id": "1881",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "326",
            "clan_rank": "0",
            "clan_name": "แอ๊บแบ๊วอุ๊อิ",
            "owner_id": "2006",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "333",
            "clan_rank": "0",
            "clan_name": "๏420",
            "owner_id": "1565",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "338",
            "clan_rank": "0",
            "clan_name": "ลําใยไหทองแดง",
            "owner_id": "2049",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "336",
            "clan_rank": "0",
            "clan_name": "BMRITOKSB2",
            "owner_id": "2038",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "328",
            "clan_rank": "0",
            "clan_name": "อิ๊ไต๊คิมูจิ๊",
            "owner_id": "1429",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "297",
            "clan_rank": "0",
            "clan_name": "OTDZA",
            "owner_id": "1772",
            "create_date": "20191104",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "322",
            "clan_rank": "0",
            "clan_name": "Hoppipp",
            "owner_id": "1966",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "339",
            "clan_rank": "0",
            "clan_name": "๑ตาโก่งขายไก่๑",
            "owner_id": "2048",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "341",
            "clan_rank": "0",
            "clan_name": "NaHe",
            "owner_id": "1614",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "340",
            "clan_rank": "0",
            "clan_name": "อาอีโนะ",
            "owner_id": "2069",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "343",
            "clan_rank": "0",
            "clan_name": "RIPLungTu",
            "owner_id": "2084",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "347",
            "clan_rank": "0",
            "clan_name": "สไนเปอร์o",
            "owner_id": "1909",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "350",
            "clan_rank": "0",
            "clan_name": "DDEsport",
            "owner_id": "1736",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "352",
            "clan_rank": "0",
            "clan_name": "รำวง",
            "owner_id": "1942",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "335",
            "clan_rank": "0",
            "clan_name": "นั๑lดีeว",
            "owner_id": "2029",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "355",
            "clan_rank": "0",
            "clan_name": "SwiKey",
            "owner_id": "2149",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "354",
            "clan_rank": "0",
            "clan_name": "JaoAoei",
            "owner_id": "2135",
            "create_date": "20191105",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "378",
            "clan_rank": "0",
            "clan_name": "NilLhoHitZ",
            "owner_id": "1660",
            "create_date": "20191107",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "360",
            "clan_rank": "0",
            "clan_name": "เดชะคำภู",
            "owner_id": "2213",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "362",
            "clan_rank": "0",
            "clan_name": "๐น้องลี่",
            "owner_id": "2229",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "364",
            "clan_rank": "0",
            "clan_name": "๓เก่งอยู่แล้ว๑",
            "owner_id": "2248",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "379",
            "clan_rank": "0",
            "clan_name": "สๅวไnบ้ๅu",
            "owner_id": "2404",
            "create_date": "20191107",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "416",
            "clan_rank": "0",
            "clan_name": "I3lack๑Hole",
            "owner_id": "2589",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "393",
            "clan_rank": "0",
            "clan_name": "DCking",
            "owner_id": "2456",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "395",
            "clan_rank": "0",
            "clan_name": "สลายฟ้า",
            "owner_id": "2515",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "426",
            "clan_rank": "0",
            "clan_name": "CGGG",
            "owner_id": "2662",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "435",
            "clan_rank": "0",
            "clan_name": "ก้มาดิ่ครับ",
            "owner_id": "2718",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "432",
            "clan_rank": "0",
            "clan_name": "อับอาย",
            "owner_id": "2675",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "477",
            "clan_rank": "0",
            "clan_name": "Devil",
            "owner_id": "2644",
            "create_date": "20191112",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "396",
            "clan_rank": "0",
            "clan_name": "JK",
            "owner_id": "2520",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "399",
            "clan_rank": "0",
            "clan_name": "KR190",
            "owner_id": "2537",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "437",
            "clan_rank": "0",
            "clan_name": "มาเป็นที่1",
            "owner_id": "2729",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "407",
            "clan_rank": "0",
            "clan_name": "อย่าร้องน่ะ",
            "owner_id": "2553",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "431",
            "clan_rank": "0",
            "clan_name": "ALONEODIN",
            "owner_id": "1534",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "408",
            "clan_rank": "0",
            "clan_name": "มืoปืน",
            "owner_id": "2547",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "275",
            "clan_rank": "0",
            "clan_name": "LeahoyUniverse",
            "owner_id": "1487",
            "create_date": "20191103",
            "partidas": "3",
            "vitorias": "0",
            "derrotas": "3",
            "pontos": "891",
            "clan_exp": "3562"
          },
          {
            "clan_id": "413",
            "clan_rank": "0",
            "clan_name": "หิมะ",
            "owner_id": "1284",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "428",
            "clan_rank": "0",
            "clan_name": "ษฌซ์ฉฉ๋ฌ๋ฌษฌณษฌษ",
            "owner_id": "2657",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "412",
            "clan_rank": "0",
            "clan_name": "gเอออหน้า",
            "owner_id": "2555",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "473",
            "clan_rank": "0",
            "clan_name": "fort123a1",
            "owner_id": "2535",
            "create_date": "20191112",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "419",
            "clan_rank": "0",
            "clan_name": "CKแปดริ่ว",
            "owner_id": "2283",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "429",
            "clan_rank": "0",
            "clan_name": "ไอหน้าโง่",
            "owner_id": "2692",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "462",
            "clan_rank": "0",
            "clan_name": "Cougargangs",
            "owner_id": "2839",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "438",
            "clan_rank": "0",
            "clan_name": "TheviperSPY",
            "owner_id": "2731",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "423",
            "clan_rank": "0",
            "clan_name": "อดีต",
            "owner_id": "2297",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "442",
            "clan_rank": "0",
            "clan_name": "ตายยา",
            "owner_id": "2588",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "425",
            "clan_rank": "0",
            "clan_name": "xscdcdcdcdvfvf",
            "owner_id": "2658",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "444",
            "clan_rank": "0",
            "clan_name": "OVERDIE",
            "owner_id": "2771",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "410",
            "clan_rank": "0",
            "clan_name": "OzoneHybridman",
            "owner_id": "1691",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "20861"
          },
          {
            "clan_id": "454",
            "clan_rank": "0",
            "clan_name": "EvolutionGvng",
            "owner_id": "2169",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "452",
            "clan_rank": "0",
            "clan_name": "DARKSIDE",
            "owner_id": "1891",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "397",
            "clan_rank": "0",
            "clan_name": "KFC",
            "owner_id": "2529",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "484",
            "clan_rank": "0",
            "clan_name": "นาเดียร์",
            "owner_id": "3016",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "475",
            "clan_rank": "0",
            "clan_name": "ชิว",
            "owner_id": "2756",
            "create_date": "20191112",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "466",
            "clan_rank": "0",
            "clan_name": "วัดธรรมกาย",
            "owner_id": "2848",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "482",
            "clan_rank": "0",
            "clan_name": "Loner",
            "owner_id": "2986",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "486",
            "clan_rank": "0",
            "clan_name": "Brightz",
            "owner_id": "2284",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "443",
            "clan_rank": "0",
            "clan_name": "๏RSV",
            "owner_id": "2752",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "372",
            "clan_rank": "0",
            "clan_name": "BlackXII",
            "owner_id": "1575",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "371",
            "clan_rank": "0",
            "clan_name": "มัจฉาฯ",
            "owner_id": "1585",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "366",
            "clan_rank": "0",
            "clan_name": "Scarlate",
            "owner_id": "1065",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "367",
            "clan_rank": "0",
            "clan_name": "XAGOD",
            "owner_id": "2087",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "414",
            "clan_rank": "0",
            "clan_name": "Renovate",
            "owner_id": "2573",
            "create_date": "20191109",
            "partidas": "4",
            "vitorias": "4",
            "derrotas": "0",
            "pontos": "1120",
            "clan_exp": "3478"
          },
          {
            "clan_id": "409",
            "clan_rank": "0",
            "clan_name": "RachYO",
            "owner_id": "2554",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "380",
            "clan_rank": "0",
            "clan_name": "xXหลวงปู่เค็มXx",
            "owner_id": "1024",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "370",
            "clan_rank": "0",
            "clan_name": "JF",
            "owner_id": "2131",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "450",
            "clan_rank": "0",
            "clan_name": "pmcanucha",
            "owner_id": "2572",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "434",
            "clan_rank": "0",
            "clan_name": "SAWADEE",
            "owner_id": "2694",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "411",
            "clan_rank": "0",
            "clan_name": "กำนัน",
            "owner_id": "2548",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "383",
            "clan_rank": "0",
            "clan_name": "EXP",
            "owner_id": "2440",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "390",
            "clan_rank": "0",
            "clan_name": "UMMASTER",
            "owner_id": "2475",
            "create_date": "20191108",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "453",
            "clan_rank": "0",
            "clan_name": "สในเปอร์",
            "owner_id": "2803",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "415",
            "clan_rank": "0",
            "clan_name": "THAILAND",
            "owner_id": "2568",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "369",
            "clan_rank": "0",
            "clan_name": "USA",
            "owner_id": "1413",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "439",
            "clan_rank": "0",
            "clan_name": "soryer",
            "owner_id": "2727",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "436",
            "clan_rank": "0",
            "clan_name": "ลั่นแจ๊ะโหดลั่น",
            "owner_id": "2152",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "441",
            "clan_rank": "0",
            "clan_name": "BHสายโหด",
            "owner_id": "2745",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "424",
            "clan_rank": "0",
            "clan_name": "AVTing",
            "owner_id": "1241",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "417",
            "clan_rank": "0",
            "clan_name": "แมวปีศาจ",
            "owner_id": "2613",
            "create_date": "20191109",
            "partidas": "1",
            "vitorias": "0",
            "derrotas": "1",
            "pontos": "960",
            "clan_exp": "42"
          },
          {
            "clan_id": "394",
            "clan_rank": "0",
            "clan_name": "สไนเปอร้",
            "owner_id": "2153",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "455",
            "clan_rank": "0",
            "clan_name": "อาปาเช่",
            "owner_id": "2810",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "427",
            "clan_rank": "0",
            "clan_name": "Ponrhub",
            "owner_id": "2594",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "445",
            "clan_rank": "0",
            "clan_name": "ฮีระเบิด",
            "owner_id": "2777",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "430",
            "clan_rank": "0",
            "clan_name": "๛๐มังกร",
            "owner_id": "2467",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "433",
            "clan_rank": "0",
            "clan_name": "RRBllesport",
            "owner_id": "1879",
            "create_date": "20191110",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "463",
            "clan_rank": "0",
            "clan_name": "wsะsามoมEิ้ม",
            "owner_id": "2837",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "456",
            "clan_rank": "0",
            "clan_name": "Wssเหล่าเด็ก",
            "owner_id": "2296",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "457",
            "clan_rank": "0",
            "clan_name": "LOSZETAS",
            "owner_id": "2815",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "363",
            "clan_rank": "0",
            "clan_name": "BlackPearl",
            "owner_id": "2239",
            "create_date": "20191106",
            "partidas": "10",
            "vitorias": "10",
            "derrotas": "0",
            "pontos": "1300",
            "clan_exp": "10019"
          },
          {
            "clan_id": "471",
            "clan_rank": "0",
            "clan_name": "อิหยังว่ะ",
            "owner_id": "2867",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "465",
            "clan_rank": "0",
            "clan_name": "Anonymus",
            "owner_id": "2853",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "459",
            "clan_rank": "0",
            "clan_name": "ซันไลน์",
            "owner_id": "2214",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "461",
            "clan_rank": "0",
            "clan_name": "สมพร",
            "owner_id": "2835",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "404",
            "clan_rank": "0",
            "clan_name": "smile",
            "owner_id": "2480",
            "create_date": "20191109",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "467",
            "clan_rank": "0",
            "clan_name": "CiTy",
            "owner_id": "2861",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "464",
            "clan_rank": "0",
            "clan_name": "ZIPPER",
            "owner_id": "1039",
            "create_date": "20191111",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "472",
            "clan_rank": "0",
            "clan_name": "ดุ๊กดิ๊ก",
            "owner_id": "2880",
            "create_date": "20191112",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "474",
            "clan_rank": "0",
            "clan_name": "๛สลาย",
            "owner_id": "2909",
            "create_date": "20191112",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "478",
            "clan_rank": "0",
            "clan_name": "Wuuเด็ก",
            "owner_id": "2941",
            "create_date": "20191112",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "481",
            "clan_rank": "0",
            "clan_name": "ไก่น้อยค่อยรอ",
            "owner_id": "2953",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "365",
            "clan_rank": "0",
            "clan_name": "AVGNBV",
            "owner_id": "2273",
            "create_date": "20191106",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "480",
            "clan_rank": "0",
            "clan_name": "StarTos",
            "owner_id": "2958",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "485",
            "clan_rank": "0",
            "clan_name": "BabyBoy",
            "owner_id": "2484",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "487",
            "clan_rank": "0",
            "clan_name": "KTZ007",
            "owner_id": "3020",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          },
          {
            "clan_id": "489",
            "clan_rank": "0",
            "clan_name": "จังไรแมน",
            "owner_id": "3023",
            "create_date": "20191113",
            "partidas": "0",
            "vitorias": "0",
            "derrotas": "0",
            "pontos": "1000",
            "clan_exp": "0"
          }  
]