export default[
    {
        "id" :0,
        "title": "Torneio FirstWinner Vagas Abertas!",
        "date" : "12.01.2021",
        "img": "/Front/Announcers/ViewImagedo3.jpg",
        "category": 2,
        "smalltext": "Dear Point Blank Players,Our maintenance took place on 12.01.2021, which started at 04:30 and was completed at 08:43, thank you for your patience and understanding during the maintenance period.The maintenance covere..",
        "content": '<ul class="bbs_view_tit"> <li class="tit">PBAC 2021 February Regıstratıon Started</li> <li class="date"> 18 February, 2021 </li> </ul> <div class="bbs_view"> <p dir="ltr"><img alt="" src="/Front/Announcers/ViewImagedo3.jpg" style="height:348px; width:730px"></p> <p dir="ltr">Point Blank Advanced cup February registration started wit the sponsorship of <a href="http://KabasakalOnline.com"><span style="color:#ff8c00"><strong>Kabasakal Online</strong></span></a>.</p> <p dir="ltr">&nbsp;</p> <p dir="ltr">At the end of the 3-day marathon, 1 team will announce their championship and will receive a cash prize of 3.500 TL.<br> <br> If you want to mark the top 3, take your place in this tournament!<br> <br> Tournament is BIG! Prize pool is bigger.<br> <br> Only 64 team registrations will be confirmed in the Point Blank Advanced Cup. To be among these teams, it is enough to submit your registration completely and correctly!<br> <br> <strong><span style="color:#ff0000">Registration Form:</span></strong> <strong><a href="http://bit.ly/PBACRegistrationForm"><span style="color:#0000ff">http://bit.ly/PBACRegistrationForm</span></a></strong><br> <span style="color:#ff0000"><strong>Registration End:</strong></span> 24th February 8pm </p> <p dir="ltr">&nbsp;</p> <p dir="ltr"><span style="color:#ff0000"><strong>Prize Pool</strong></span></p> <p dir="ltr"><strong><span style="color:#0000ff">1st Team:</span></strong> 3.500 TL cash prize pool<br> <span style="color:#0000ff"><strong>2nd Team:</strong></span> 2.300 TL cash prize pool<br> <strong><span style="color:#0000ff">3rd.Team:</span></strong> 1.200 TL cash prize pool </p> <p dir="ltr"><strong><span style="color:#0000ff">4th-8th Teams:</span></strong> 20.000 TG<br> <br> With many payment options, the address of speed and reliability, <a href="http://KabasakalOnline.com"><span style="color:#ff8c00"><strong>Kabasakal online</strong></span></a> is with you.<br> &nbsp; </p> <p dir="ltr"><span style="color:#ff0000"><strong>Tournament Dates</strong></span></p> <p dir="ltr"><br> <strong><span style="color:#0000ff">26th February Friday 6pm(Match Start): </span></strong>Elimination Phase(until quarter finals) </p> <p dir="ltr"><span style="color:#0000ff"><strong>27th February Saturday 6pm(Match Start):</strong></span> Quarter Finals - Semi Finals - Losers Bracket</p> <p><span style="color:#0000ff"><strong>28th February Sunday 6pm:</strong></span> Losers Bracket Final and Grand Final</p> </div> <div class="cont_btn"> <p class="btn"><span class="btn_cont_w135"><a class="btn" href="javascript:void(0);" onclick="List();">List</a></span></p> </div>'
    }
]